### PR TITLE
Add slack badge

### PR DESCRIPTION
**Pull request by anandswaminathan**
Directs to https://flinkk8soperator.slack.com

### CODE REVIEW

**Comment by mwylde** [comment]
As a not-logged in user, I get this when I go to that link:
image

which doesn't make it obvious how to get an account. For example, Apache uses https://s.apache.org/slack-invite as its link, which for not-logged in users goes to an account creation flow. We should at least document the process.

**Comment by anandswaminathan** [comment]
@mwylde  Can you try now ?

**Comment by mzuehlke** [comment]
**This invite link is no longer active.**

**Comment by anandswaminathan** [comment]
@mzuehlke 
Try this
https://join.slack.com/t/flinkk8soperator/shared_invite/enQtNzgyNzg5NzIwNDg0LWIzMjIxNjUxYTA3ZmE5MTMyNDZlMmRlYmM4ZGQ1OTM1NmUxOTJmMTY0NjI2ZDE4YjE0ZDM4Y2Q1YjgxYmUyNzI

**Comment by mzuehlke** [comment]
That link works. Thanks 👍

**Pull request merged**
