### PR TITLE
Enabling PodSecurityContext to be configured for JM and TM pod templates

### PR DESCRIPTION
**Pull request by kelly-sm**
* Updating the CRD to enable pod security context to be specified and applied to JM and TM pods.

* Adding security context fields to crd validation.

* Changing security context injection to maintain hash-based backwards compatibility.

* Adding tests to ensure that security context is being injected properly.

### CODE REVIEW

**Comment by anandswaminathan** [comment]
+1 LGTM

**Comment by kelly-sm** [comment]
Is there a way to pull an image of this once it is merged in? Does each commit get built and pushed somewhere?

**Comment by anandswaminathan** [comment]
@kelly-sm Once you merge. Image gets pushed from Travis. 

You can pull the image from `docker.io/lyft/flinkk8soperator:{sha}`

**Comment by kelly-sm** [comment]
@anandswaminathan sounds good. Sounds like we just need another person to review/approve?

Thanks!

**Pull request merged**
