### PR TITLE
Various minor fixes

### PR DESCRIPTION
**Pull request by yuchaoran2011**
* `omitempty` is the right tag name. Note the lowercase `e`.
* config strings should be camel case, with the first letter lowercase.
* Updated the example wordcount to use Flink 1.9.1
* Go version update to 1.13.4.

### CODE REVIEW

**Comment by yuchaoran2011** [comment]
I wonder why the lint job failed because `make lint` ran without errors on my local machine. I'm using Go 1.13.4.  Is it a transient error, in which case could an admin trigger a re-run? Or is it something wrong with Travis? Let me know if it's something in the PR that I can fix. Thanks!

**Comment by skonto** [comment]
This requires the new version for golangci-lint/ as described[ here](https://github.com/golangci/golangci-lint/issues/663#issuecomment-529871239).

**Comment by yuchaoran2011** [comment]
Admins, as @skonto pointed out above, `golangci-lint` in travis is outdated. Do you think you guys can easily upgrade that? If not, I'll revert the upgrade to Go 1.13.4 to make the build pass.

**Comment by mwylde** [comment]
Yeah, for now I would revert the change to 1.13. I'll look into what's required to update golangci-lint.

**Comment by yuchaoran2011** [comment]
@mwylde Thanks! Done. The build is now passing.

**Pull request merged**
