### PR TITLE
Introduce affinity field

### PR DESCRIPTION
**Pull request by gydtaai**
Add affinity field to taskManagerConfig and jobManagerConfig to be able to set up affinity on pods.
Affinity fields are pass to the corresponding deployments.

openAPIV3Schema of affinity is built based on k8s open api.

### CODE REVIEW

**Comment by anandswaminathan** [comment]
@gydtaai CLA?

**Comment by gydtaai** [comment]
> @gydtaai CLA?

I need approval from my employer.  I am trying to manage.

**Comment by gydtaai** [comment]
Hi @anandswaminathan,
I could accept CLA. Please let me know if I need to add anything else.
Thanks

**Review by anandswaminathan — APPROVED** [review]

**Comment by maghamravi** [comment]
Thanks @gydtaai for the effort!

**Review by maghamravi — APPROVED** [review]

**Pull request merged**
